openapi: 3.0.3
info:
  description: Food Production Common API based on Reference Architectural Model Industrie
    4.0 (RAMI 4.0)
  title: Food Production Common API
  version: 1.0.0
servers:
- url: http://localhost:8000/
paths:
  /soil/nutrients:
    post:
      description: "Raw sensor payment received in the integration layer and converted\
        \ into \nthis common model to generate an event for the information layer.\n"
      operationId: soilNutrientsPOST
      requestBody:
        content:
          application/json:
            examples:
              NutrientExample:
                $ref: '#/components/examples/NutrientExample'
            schema:
              $ref: '#/components/schemas/Nutrient'
          application/xml:
            schema:
              $ref: '#/components/schemas/Nutrient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Nutrient'
      responses:
        "201":
          description: Event successfully sent
      summary: Soil nutrient measurement event
      x-eov-operation-handler: controllers/DefaultController
  /soil/conditions:
    post:
      description: "Raw sensor payment received in the integration layer and converted\
        \ into \nthis common model to generate an event for the information layer.\n"
      operationId: soilConditionsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Condition'
          application/xml:
            schema:
              $ref: '#/components/schemas/Condition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Condition'
      responses:
        "201":
          description: Event successfully sent
      summary: Soil conditions measurement event
      x-eov-operation-handler: controllers/DefaultController
  /soil/compositions:
    post:
      description: "Raw sensor payment received in the integration layer and converted\
        \ into \nthis common model to generate an event for the information layer.\n"
      operationId: soilCompositionsPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Composition'
          application/xml:
            schema:
              $ref: '#/components/schemas/Composition'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Composition'
      responses:
        "201":
          description: Event successfully sent
      summary: Soil composition measurement event
      x-eov-operation-handler: controllers/DefaultController
  /weather/temperature:
    post:
      description: "Raw sensor payment received in the integration layer and converted\
        \ into \nthis common model to generate an event for the information layer.\n"
      operationId: weatherTemperaturePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Temperature'
          application/xml:
            schema:
              $ref: '#/components/schemas/Temperature'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Temperature'
      responses:
        "201":
          description: Event successfully sent
      summary: Soil composition measurement event
      x-eov-operation-handler: controllers/DefaultController
  /weather/precipitation:
    post:
      description: "Raw sensor payment received in the integration layer and converted\
        \ into \nthis common model to generate an event for the information layer.\n"
      operationId: weatherPrecipitationPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Precipitation'
          application/xml:
            schema:
              $ref: '#/components/schemas/Precipitation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Precipitation'
      responses:
        "201":
          description: Event successfully sent
      summary: Soil composition measurement event
      x-eov-operation-handler: controllers/DefaultController
components:
  examples:
    NutrientExample:
      value:
        header:
          sensorId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          time: 2024-03-27T17:33:31.482Z
          fieldId: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        phosphorus: 5
        nitrogen: 12
        potassium: 8
        calcium: 8
        magnesium: 5
        sulfur: 1
        salt: 12
        zinc: 2
        iron: 4
  schemas:
    Header:
      example:
        time: 2000-01-23T04:56:07.000+00:00
        farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        sensorId:
          format: uuid
          type: string
        time:
          format: date-time
          type: string
        fieldId:
          format: uuid
          type: string
        farmId:
          format: uuid
          type: string
      type: object
    Nutrient:
      example:
        potassium: 1.4658129805029452
        calcium: 5.962133916683182
        salt: 7.061401241503109
        nitrogen: 6.027456183070403
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        magnesium: 5.637376656633329
        sulfur: 2.3021358869347655
        iron: 3.616076749251911
        zinc: 9.301444243932576
        phosphorus: 0.8008281904610115
      properties:
        header:
          $ref: '#/components/schemas/Header'
        phosphorus:
          format: ppm
          type: number
        nitrogen:
          format: ppm
          type: number
        potassium:
          format: ppm
          type: number
        calcium:
          format: ppm
          type: number
        magnesium:
          format: ppm
          type: number
        sulfur:
          format: ppm
          type: number
        salt:
          description: |
            Soil salinity is measured in units of electrical conductivity (EC), which is also known as Siemens (S).
            The most common units of EC are deciSiemens per meter (dS/m)
          format: dS/m
          type: number
        zinc:
          format: ppm
          type: number
        iron:
          format: ppm
          type: number
      type: object
    Composition:
      example:
        heavyMetals: 6.027456183070403
        organicMass: 8.008281904610115
        granularity: 5.962133916683182
        soilType: Gravel
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        microbialActivity: 1.4658129805029452
      properties:
        header:
          $ref: '#/components/schemas/Header'
        organicMass:
          description: biomass as a % of soil
          format: '%'
          maximum: 100
          minimum: 0
          type: number
        heavyMetals:
          format: ug/kg or ppb
          type: number
        microbialActivity:
          format: mg/kg
          type: number
        granularity:
          description: |
            Percentage of fine grains to weight
            Higher percentage of file grains means the soil is more cohesive (more clay).
            Lower % of fine grains mean the soil is more granular
          format: '%'
          type: number
        soilType:
          description: |
            Gravel: >2.0mm
            Very coarse: 1.0 - 2.0mm
            Coarse: 0.50 - 1.0mm
            Medium: 0.25 - 0.50mm
            Fine: 0.10 - 0.25mm
            Very fine: 0.05 - 0.10mm
          enum:
          - Gravel
          - Very coarse
          - Coarse
          - Medium
          - Fine
          - Very fine
          type: string
      type: object
    Condition:
      example:
        sunlight: 1.4658129805029452
        ph: 8.438438656298565
        temperature: 5.962133916683182
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        soilHumidity: 8.008281904610115
      properties:
        header:
          $ref: '#/components/schemas/Header'
        soilHumidity:
          description: Volumetric water content
          format: '%'
          maximum: 100
          minimum: 0
          type: number
        ph:
          maximum: 14
          minimum: 0
          type: number
        sunlight:
          format: W/m^2
          type: number
        temperature:
          format: Â°C
          type: number
      type: object
    Temperature:
      example:
        duration: 6.027456183070403
        level: 0.8008281904610115
        timing: 2000-01-23T04:56:07.000+00:00
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        header:
          $ref: '#/components/schemas/Header'
        timing:
          format: date-time
          type: string
        level:
          type: number
        duration:
          type: number
      type: object
    Precipitation:
      example:
        duration: 6.027456183070403
        intensity: intensity
        amount: 0.8008281904610115
        timing: 2000-01-23T04:56:07.000+00:00
        header:
          time: 2000-01-23T04:56:07.000+00:00
          farmId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          sensorId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          fieldId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        distribution: distribution
        variability: variability
        evaporation: 1.4658129805029452
      properties:
        header:
          $ref: '#/components/schemas/Header'
        timing:
          format: date-time
          type: string
        amount:
          type: number
        duration:
          type: number
        distribution:
          type: string
        evaporation:
          type: number
        intensity:
          type: string
        variability:
          type: string
      type: object
